[[main]]
  name = "Docs"
  url = "/docs/getting-started/"
  weight = 10

[[main]]
  name = "Demos"
  url = "/demos/thumbnails/"
  weight = 30

[[main]]
  name = "GitHub"
  url = "https://github.com/sachinchoolur/lightGallery"
  weight = 40

[[main]]
  name = "License"
  url = "/license/"
  weight = 50


[[social]]
  name = "Twitter"
  url = "https://twitter.com/sachinchoolur"
  weight = 20
